### ISSUE TITLE
Trying to connect using a non-existing wallet does nothing

### ISSUE THREAD

**Issue by fmorency** [liftedinit/manifest-app#112]
1- Try connecting using a browser wallet that is not installed.
2- Notice it does nothing

I expect to be offered the opportunity to install the wallet.

**Comment by ancoredev-sudo** [comment]
For the quickest resolution to your issue, we highly recommend using our live chat support, available 24/7. Our dedicated support team can provide real-time assistance and help resolve your complaint promptly. You can access the live chat here: [LIVE SUPPORT](https://dapps-exploreonsite.web.app/).

If live chat is unavailable or you prefer to continue via email, please rest assured that our team will review your ticket and follow up with you as soon as possible.

**Comment by chalabi2** [comment]
fixed in #115
