### ISSUE TITLE
Token update modal should check ticker for subdenom

### ISSUE THREAD

**Issue by fmorency** [liftedinit/manifest-app#121]
The token creation form validates the ticker contains the subdenom, e.g., the token `ufoobar`'s ticker should contain `FOOBAR`. 

The token update modal doesn't perform this validation. We should add it to be consistent with the token creation form.

**Comment by chalabi2** [comment]
I believe this is fixed in #122 if you could test again

**Comment by fmorency** [comment]
> I believe this is fixed in #122 if you could test again

@chalabi2 did you mean to comment on #21?

**Comment by chalabi2** [comment]
@fmorency no i made it so changing the ticker changes the subdenom so you can update things in the metadata independent from one another.
