### ISSUE TITLE
Pagination?

### ISSUE THREAD

**Issue by fmorency** [liftedinit/manifest-app#15]
Not sure if it's already the case but the group list on the `group` page should be paginated. Same for the tokens listed on the `token factory` page.

**Comment by chalabi2** [comment]
I understand the concern because having excessive groups and tokens will impact load times but wont it also break the search functionality? I believe theres potentially a way around that will look into it

**Comment by fmorency** [comment]
I would load them all but paginate the display. I might be wrong but I don't think we'll get to a point where excessive groups and tokens will impact load times... at least not shortly.

**Comment by chalabi2** [comment]
group pagination fixed in #92

**Comment by chalabi2** [comment]
#94 finishes this issue
