### ISSUE TITLE
Refresh token factory page on update

### ISSUE THREAD

**Issue by fmorency** [liftedinit/manifest-app#22]
After minting, burning, or updating a token, the page should be refreshed, and up-to-date information should be displayed.

![2024-11-12_09-41_2](https://github.com/user-attachments/assets/76b4b55a-089d-4ce8-90f1-cee67b2faf9d)

**Comment by chalabi2** [comment]
hey just need to add the refetch call to the onSuccess section of the transaction hook, tracking now
