### ISSUE TITLE
Token metadata update modal should be initialized with current metadata

### ISSUE THREAD

**Issue by fmorency** [liftedinit/manifest-app#23]
The token metadata update modal is currently initialized with empty values. Instead, current values should be fetched from the chain and displayed.

![2024-11-12_10-07](https://github.com/user-attachments/assets/6999b9aa-4164-450b-a0f3-f226c1eecc01)

**Comment by chalabi2** [comment]
tracking

**Comment by chalabi2** [comment]
fixed in #77
