### ISSUE TITLE
Uniformize modal look'n'feel

### ISSUE THREAD

**Issue by fmorency** [liftedinit/manifest-app#30]
We have a couple of different designs and layouts for the modal. We should uniformize everything.

Note: personally, I wouldn't say I like how the buttons are displayed in the first image below. It feels like they're not attached to anything.

![2024-11-12_11-03](https://github.com/user-attachments/assets/221cb34c-4c82-4df6-a071-2c60f361acca)
![2024-11-12_11-03_1](https://github.com/user-attachments/assets/96520d08-de12-476b-861b-df4972bd4202)
![2024-11-12_11-04](https://github.com/user-attachments/assets/d715dab3-6190-4c75-984a-181ce4ce1312)

**Comment by chalabi2** [comment]
the update metadata modal was following the designs but I do agree it would be better with the buttons in the modal. Tracking

**Comment by fmorency** [comment]
> the update metadata modal was following the designs but I do agree it would be better with the buttons in the modal. Tracking

Thanks! Yeah, the design from Costa is still a moving target, not a finality.

**Comment by chalabi2** [comment]
fixed in #77
