### ISSUE TITLE
Link in the transaction detail should point to the block explorer

### ISSUE THREAD

**Issue by fmorency** [liftedinit/manifest-app#31]
The correct block explorer should be used and depends on the selected endpoint.

Using a local instance, the link is incorrectly pointing to 

http://localhost:3000/undefined/transaction/D55D7A5DEF7326B673E7096BABABE51D95D73EF46109B5F14868612AD2D0D54A

![2024-11-12_11-08](https://github.com/user-attachments/assets/2b800ff0-dca9-406a-a078-24b587a9201e)

**Comment by chalabi2** [comment]
tracking, will point it to node guru exploer

**Comment by chalabi2** [comment]
you need to add 

NEXT_PUBLIC_TESTNET_EXPLORER_URL=https://testnet.manifest.explorers.guru to .env

The functionality is already implemented added an example env
