### ISSUE TITLE
Proposal not shown

### ISSUE THREAD

**Issue by fmorency** [liftedinit/manifest-app#34]
I created a new proposal (POA Group) using the proposal wizard. After the confirmation screen, I was brought back to the proposal page where the proposal list was empty. I attempted a page refresh without luck. I can see the proposal was processed in the block explorer [1].

[1]: https://testnet.manifest.explorers.guru/transaction/53299378ECF8731EDAFE396F4556EB5A0CD210BBA343429B8A2672F775CAFE8D?height=538394

![2024-11-12_11-22](https://github.com/user-attachments/assets/80c8c9cb-7715-4490-8b90-496c09eb840a)

**Comment by fmorency** [comment]
This issue stems from setting `exec: 1` in `MsgSubmitProposal`.

Setting it to `0` fixes the problem.

More testing and investigation required.

**Comment by chalabi2** [comment]
exec 1 means the proposal will be executed immediately. Dont think theres an issue here just need to make sure the ui uses strictly 0. Its built to catch each specific status and provide the button for interacting with said status. Closing this for now
