### ISSUE TITLE
One should be able to withdraw one's ownproposal

### ISSUE THREAD

**Issue by fmorency** [liftedinit/manifest-app#51]
One should be able to withdraw one's own proposal without requiring another proposal.

The "Withdraw proposal" message should be removed from the proposal creation UI.

**Comment by fmorency** [comment]
One is already capable of doing so. I removed the message from the proposal creation UI in #53.

**Comment by chalabi2** [comment]
this already a feature in the votedetailsmodal 

https://github.com/liftedinit/manifest-app/blob/bbf797d2718bb5f58330a5a71f69f12013e29380/components/groups/modals/voteDetailsModal.tsx#L575
