### ISSUE TITLE
Group transaction history

### ISSUE THREAD

**Issue by fmorency** [liftedinit/manifest-app#55]
One needs to be able to view the transaction history of a given group.

**Comment by chalabi2** [comment]
This relates to the overall redesign of the group proposal page we spoke about. I think this should be apart of a different milestone which could potentially include the bank page redesigns. 

Lets chat more about this and issue #44 this week?

**Comment by chalabi2** [comment]
added in #127

**Comment by fmorency** [comment]
Fixed by #127
