### ISSUE TITLE
Wrong balance displayed

### ISSUE THREAD

**Issue by fmorency** [liftedinit/manifest-app#56]
This is a number manipulation issue.

The first image is from Alberto (wrong) and the second image is from the block explorer (correct).

![2024-11-18_16-06](https://github.com/user-attachments/assets/f9724689-c284-4c87-9068-d5b6778fee02)
![2024-11-18_16-06_1](https://github.com/user-attachments/assets/d69c13ec-a7d1-4ad5-8325-33c1a5773a70)

**Comment by chalabi2** [comment]
Are you sure the block explorer isnt rounding? They only show four decimals where the actual amount would have 6 which makes me think they are rounding and we are not

**Comment by fmorency** [comment]
> Are you sure the block explorer isnt rounding? They only show four decimals where the actual amount would have 6 which makes me think they are rounding and we are not

Not a rounding error

```shell
➜  ~ ~/go/bin/manifestd q bank balance manifest1afk9zr2hn2jsac63h4hm60vl9z3e5u69gndzf7c99cqge3vzwjzsfmy9qj umfx --node https://nodes.liftedinit.tech/manifest/testnet/rpc
balance:
  amount: "99398999995"
  denom: umfx
```

I can tackle this one. Numbers are hard, man.
