### ISSUE TITLE
Unable to see full Proposal message

### ISSUE THREAD

**Issue by fmorency** [liftedinit/manifest-app#63]
One should be able to view the full extent of the proposal message.

![2024-11-19_15-46](https://github.com/user-attachments/assets/e11c8999-8ebe-46b0-a2b6-cc1a4de0315b)

**Comment by chalabi2** [comment]
Do you mind if that box becomes very scroll heavy? If not im happy to do this. Otherwise  i need to think of a different way to display

**Comment by fmorency** [comment]
> Do you mind if that box becomes very scroll heavy? If not im happy to do this. Otherwise i need to think of a different way to display

Let's discuss this live.

It might be simpler just to add a button to display the raw message content instead.

**Comment by chalabi2** [comment]
fixed message displays in #96 - also added expanded message view in #96
