### ISSUE TITLE
Mobile Wallet vertical display

### ISSUE THREAD

**Issue by fmorency** [liftedinit/manifest-app#70]
The vertical display of the "Connect Wallet" modal doesn't show social login options.

Pixel 6.

![signal-2024-11-25-110709_003](https://github.com/user-attachments/assets/60412b04-7c89-4959-b91a-973469ab5e44)

**Comment by chalabi2** [comment]
check social logins work on mobile

ensure social options aren't available on mobile or tablet / landscape

**Comment by chalabi2** [comment]
fixed in #89
